[package]
name = "rustile"
version = "0.1.0"
edition = "2024"

[dependencies]
x11rb = "0.13.0"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
xkeysym = "0.2.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
