# Example configuration file for Rustile window manager
# Copy this file to ~/.config/rustile/config.toml and customize as needed

[general]
# Default display for launching applications
default_display = ":1"

[layout]
# Master window ratio (0.0 to 1.0)
# 0.5 means master window takes 50% of screen width
master_ratio = 0.5

# Gap between windows in pixels
gap = 10

# Window border settings
border_width = 5               # Border width in pixels
focused_border_color = 0xFF0000   # Red color for focused window (hex format)
unfocused_border_color = 0x808080 # Gray color for unfocused windows (hex format)

[shortcuts]
# Format: "Modifier+Key" = "command"
# 
# Available modifiers:
#   Primary: Super, Alt, Ctrl, Shift
#   Alternative names: Win/Windows/Cmd (for Super), Meta (for Alt), Control/Ctl (for Ctrl)
#   Less common: Mod2/NumLock, Mod3/ScrollLock, Mod5/AltGr
#   Special: Hyper (combines Super+Alt+Ctrl+Shift)
#
# You can combine multiple modifiers like "Ctrl+Alt+t" or "Super+Shift+Alt+F12"
# Case insensitive: "SUPER+T", "super+t", "Super+t" all work the same

# Application shortcuts
"Shift+Alt+1" = "gnome-terminal"
"Shift+Alt+2" = "code"
"Shift+Alt+3" = "chrome"

# Window focus and navigation shortcuts  
"Alt+j" = "focus_next"        # Focus next window
"Alt+k" = "focus_prev"        # Focus previous window
"Shift+Alt+m" = "swap_with_master"  # Swap focused window with master