# Example configuration file for Rustile window manager
# Copy to ~/.config/rustile/config.toml to customize

[layout]
bsp_split_ratio = 0.5      # Split ratio for new windows (0.0-1.0)
min_window_width = 100      # Minimum window width in pixels
min_window_height = 50      # Minimum window height in pixels
gap = 10                    # Gap between windows in pixels (0-500)
border_width = 5            # Border width in pixels (1-50)
focused_border_color = 0xFF0000    # Red for focused window
unfocused_border_color = 0x808080  # Gray for unfocused windows

[shortcuts]
# Available modifiers: Super, Alt, Ctrl, Shift
# Can combine: "Ctrl+Alt+t" or "Super+Shift+j"

# Application shortcuts
"Shift+Alt+1" = "xterm"
"Shift+Alt+2" = "emacs"
"Shift+Alt+3" = "google-chrome --disable-gpu"

# Window management
"Alt+j" = "focus_next"        # Focus next window
"Alt+k" = "focus_prev"        # Focus previous window
"Shift+Alt+j" = "swap_window_next"  # Swap with next window
"Shift+Alt+k" = "swap_window_prev"  # Swap with previous window
"Shift+Alt+q" = "destroy_window"    # Close focused window
"Alt+f" = "toggle_fullscreen"       # Toggle fullscreen
"Alt+r" = "rotate_windows"          # Rotate split direction
"Alt+d" = "toggle_zoom"             # Toggle zoom to parent