# Example configuration file for Rustile window manager
# Copy this file to ~/.config/rustile/config.toml and customize as needed

[general]
# Default display for launching applications
default_display = ":10"

[layout]
# BSP (Binary Space Partitioning) layout settings
# Default split ratio for new BSP splits (0.0 to 1.0)
# 0.5 means equal 50/50 split between windows
bsp_split_ratio = 0.5

# Minimum window dimensions in pixels
# Prevents windows from becoming too small to be usable
min_window_width = 100   # Minimum width for any window (recommended: 80-150)
min_window_height = 50   # Minimum height for any window (recommended: 40-80)

# Gap between windows in pixels
# Recommended values: 0-50 (0 = no gaps, 10-20 = comfortable, 50+ = spacious)
# Maximum allowed: 500 pixels
gap = 10

# Window border settings
# Recommended border_width: 1-10 (1-3 = subtle, 4-6 = visible, 7-10 = bold)
# Maximum allowed: 50 pixels, gap + border_width max: 600 pixels combined
border_width = 5               # Border width in pixels
focused_border_color = 0xFF0000   # Red color for focused window (hex format)
unfocused_border_color = 0x808080 # Gray color for unfocused windows (hex format)

[shortcuts]
# Format: "Modifier+Key" = "command"
# 
# Available modifiers:
#   Primary: Super, Alt, Ctrl, Shift
#   Alternative names: Win/Windows/Cmd (for Super), Meta (for Alt), Control/Ctl (for Ctrl)
#   Less common: Mod2/NumLock, Mod3/ScrollLock, Mod5/AltGr
#   Special: Hyper (combines Super+Alt+Ctrl+Shift)
#
# You can combine multiple modifiers like "Ctrl+Alt+t" or "Super+Shift+Alt+F12"
# Case insensitive: "SUPER+T", "super+t", "Super+t" all work the same

# Application shortcuts
"Shift+Alt+1" = "xterm"
"Shift+Alt+2" = "code"
"Shift+Alt+3" = "chrome"

# Window focus and navigation shortcuts  
"Alt+j" = "focus_next"        # Focus next window
"Alt+k" = "focus_prev"        # Focus previous window
"Shift+Alt+j" = "swap_window_next"  # Swap focused window with next window
"Shift+Alt+k" = "swap_window_prev"  # Swap focused window with previous window
"Shift+Alt+q" = "destroy_window"    # Close/destroy focused window
"Alt+f" = "toggle_fullscreen"       # Toggle fullscreen for focused window
"Alt+r" = "rotate_windows"          # Rotate focused window's parent split direction